### ISSUE TITLE
Enable GPIO buttons in PostprocessMessage

### ISSUE THREAD

**Issue by qwertyFrank** [reuterbal/photobooth#76] opened 2019-01-02 10:05 UTC
Hi,
Great project. Thanks a lot for your distribution. However I would like to use a button for printing instead using touch or mouse.
In #26 you describe in principal how it may work to add such button in GPIO interface.
Can you provide the code how to do it in which files?
Would be great.

PS: using rpi 3B+ with picamera and CP1300 printer

Thanks
Frank

**Comment by reuterbal** [comment] 2019-01-10 20:54
Sorry, at the moment I don't have the time for that. Maybe someone else would like to add this?!

**Comment by reuterbal** [comment] 2019-01-10 21:05
This is actually a duplicate of #58

**Closed by reuterbal** 2019-01-10 21:05 UTC
Labels: duplicate
