### ISSUE TITLE
Canon selphy cp 1300 / without white border

### ISSUE THREAD

**Issue by qwertyFrank** [reuterbal/photobooth#96] opened 2019-01-26 23:25 UTC
Hi,
How to enable full picture print mode for Canon selphy cp series? I.e. not printing  white border line?
Thanks

**Comment by reuterbal** [comment] 2019-01-28 08:43
Duplicate of #69. See the infos in there and please help in figuring this out.

**Closed by reuterbal** 2019-01-28 08:43 UTC
