### ISSUE TITLE
Coundown slow

### ISSUE THREAD

**Issue by karatektus** [reuterbal/photobooth#49] opened 2018-08-23 16:20 UTC
The Countdown is very slow. It should be x seconds but its taking much longer

**Comment by reuterbal** [comment] 2018-08-23 18:58
What hardware are you using? What do you mean by "much longer"?

I can confirm on my Raspberry Pi 3B that the countdown is a little bit slower than the actual count in seconds - however, it's more like in the order of <10% and not "much longer". As this is not meant as a precise chronometer but simply a hint for the user, I don't consider this to be a real issue.

**Comment by karatektus** [comment] 2018-08-23 19:10
i just stopped the time... i set the countdown timer to 2 and it literally takes 10 seconds to count down (from 2)

**Comment by reuterbal** [comment] 2018-08-23 19:45
I did the same - 8 seconds counter, 8.14 on my stopwatch. 

Can you please fill out the entire [bug report template](https://raw.githubusercontent.com/reuterbal/photobooth/master/.github/ISSUE_TEMPLATE/bug_report.md)? I need to know your camera, software versions, which bindings you use, etc. Otherwise it is just plain guesswork.

Is your RasPi a fresh install? Are you using it for anything else?

**Comment by karatektus** [comment] 2018-08-23 19:54
its a fresh install... i just noticed the countdown gets way slower once the liveview has started

**Comment by reuterbal** [comment] 2018-08-23 19:54
> Can you please fill out the entire bug report template? I need to know your camera, software versions, which bindings you use, etc. Otherwise it is just plain guesswork.

**Comment by reuterbal** [comment] 2018-09-02 11:31
It seems the issue author is not interested in providing more details. Closing this due to inacitivity.

**Closed by reuterbal** 2018-09-02 11:31 UTC
