### ISSUE TITLE
Single Button Printing

### ISSUE THREAD

**Issue by smarquis** [reuterbal/photobooth#99] opened 2019-01-30 16:53 UTC
Hi Retuerbal,

Thanks for the recent help with issue #94, i really appreciate it! I'm getting so close to having a pseudo-success story ready to go, I just need to figure out one more thing with my specific set up: 

Like a few other users on this project, I have tried implementing a single button on the front of the photobooth to trigger the camera, but I also want to be able to print from the same button so that it makes it as simple as possible for the user to understand the photobooth without screwing something up.

What i'm finding an issue with is how exactly printing takes place.

 I've been able to figure out how to re-activate the trigger gpio button once I get into the postprocessState (i.e. the screen after the pictures are taken and the print button is activated), but I can't seem to understand what happens once a user presses the print button on that same screen so that I could make the trigger button do the same thing. What specific functions get called when you click the print button with a mouse? Is there a specific file that handles when the 'print' box is clicked? I've been able to re-activate the trigger button and light in StateMachine.py, and understand all the rest of the states in StateMachine, but I don't understand how printing gets taken care of in StateMachine.py since it doesn't look like there's a class in there that deals with it.

I guess more generally, do you think you'd be able to outline what files or functions get called when you press the print button? Expanding on that, how could I make it so that when the trigger button is activated, I send a call for printing, then de-activate the trigger button?

Thank you so much for any help! 

-Smarquis

**Comment by reuterbal** [comment] 2019-01-31 08:52
Hi @smarquis 
please have a look at issue #26. There I have explained quite a bit about what would have to be done in order to make printing happen via button. Related are also #44 and #58.
I hope I will be able to finally deliver that state chart, it should make things easier to comprehend.
I'll close this as it is a duplicate of these issues above.

**Closed by reuterbal** 2019-01-31 08:52 UTC
